## Import Dataset

In [2]:
import pandas as pd

# akses data melalui url
data_url = 'https://thinkjubilee.com/bola.csv'
pd.read_csv(data_url)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

## Boolean Mask

In [ ]:
pemainbola = pd.read_csv('https://thinkjubilee.com/bola.csv')
pemainbola['market_value'] > 50

0       True
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool

In [ ]:
# tampilan lebih lengkap
pemainbola[pemainbola['market_value'] > 50]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

In [ ]:
# tampilan lebih ringkas
pemainbola[pemainbola['market_value'] > 50].shape

(6, 17)

## Method unique()
mengambil data unik gak ada yang sama

In [ ]:
# method unique
pemainbola['nationality'].unique()

array(['Chile', 'Germany', 'Czech Republic', 'England', 'France', 'Spain',
       'Nigeria', 'Switzerland', 'Wales', 'Brazil', 'Egypt', 'Argentina',
       'Colombia', 'Bosnia', 'Norway', 'Poland', 'Scotland', 'Congo DR',
       'Ireland', 'Netherlands', 'Australia', "Cote d'Ivoire", 'Finland',
       'Cameroon', 'Austria', 'Israel', 'Northern Ireland', 'Canada',
       'Belgium', 'Iceland', 'Serbia', 'Portugal', 'Ghana', 'South Korea',
       'Mali', 'Senegal', 'Curacao', 'Denmark', 'Slovenia',
       'Trinidad and Tobago', 'Bermuda', 'Benin', 'Algeria', 'Jamaica',
       'Japan', 'Tunisia', 'Croatia', 'Estonia', 'Ecuador', 'Armenia',
       'Italy', 'Sweden', 'United States', 'Morocco', 'The Gambia',
       'Kenya', 'Greece', 'Uruguay', 'Romania', 'Venezuela',
       'New Zealand'], dtype=object)

In [ ]:
# mengetahui jumlah negara yang unik
pemainbola['nationality'].unique().size

61

## Method isin()
untuk mengetahui data-data yang berada pada kriteria tertentu

In [ ]:
# tampilan bolean mask
pemainbola['nationality'].isin(['Englang','South Korea','Italy'])

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: nationality, Length: 465, dtype: bool

In [ ]:
# tampilan secara lengkap
pemainbola[pemainbola['nationality'].isin(['Englang','South Korea','Italy'])]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
131,Lee Chung-yong,Crystal+Palace,29,RW,1,1.5,327,4.5,0.10%,24,4,South Korea,0,4,6,0,0
276,Matteo Darmian,Manchester+United,27,RB,3,12.0,1640,5.5,0.30%,70,2,Italy,0,3,12,1,0
326,Manolo Gabbiadini,Southampton,25,CF,1,15.0,2012,7.0,5.20%,38,2,Italy,0,3,14,0,0
365,Ki Sung-yueng,Swansea,28,DM,2,7.0,478,5.0,0.00%,41,4,South Korea,0,4,16,0,0
383,Son Heung-min,Tottenham,25,LW,1,30.0,2185,8.0,1.60%,174,4,South Korea,0,3,17,1,0
412,Stefano Okaka,Watford,27,CF,1,6.0,708,5.5,0.20%,43,2,Italy,0,3,18,0,1
458,Angelo Ogbonna,West+Ham,29,CB,3,9.0,247,4.5,1.10%,45,2,Italy,0,4,20,0,0

## Method between()
mendapatkan range nilai dari dataset. Butuh 2 argumen --> nilai terendah & nilai tertinggi

In [ ]:
pemainbola[pemainbola['market_value'].between(65,75)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1

## Operator dan Method Perbanndingan
digunakan untuk memfilter dataset. operatornya adalah ==,>,<, dsb

In [4]:
pemainbola = pd.read_csv('https://thinkjubilee.com/bola.csv')

# para pemain dengan usia dibawah 30 tahun
pemainbola[pemainbola['age'] < 30]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [5]:
# kurang dari (<) setara dengan method lt()
pemainbola[pemainbola['age'].lt(30)]

# le() setara dengan <=
# lt() setara dengan <
# gt() setara dengan >
# ge() setara dengan >=
# eq() setara dengan ==

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [6]:
# kombinasi lebih 2 kondisi
pemainbola[(pemainbola['market_value'] > 50) & (pemainbola['nationality'] == 'England')]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

In [7]:
# buat lebih spesifik lagi
pemainbola[
    (pemainbola['market_value'] > 50) &
    (pemainbola['nationality'] == 'England') &
    (pemainbola['age'] < 30)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

In [8]:
# manfaatkan variabel biar gak terlalu pusing
usia = pemainbola['age'] < 30
klub = pemainbola['club'] == 'Arsenal'
market = pemainbola['market_value'] > 30

# terapkan ke penampil
pemainbola[usia & klub & market]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
15,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
31,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0

In [10]:
# gunakan operator NOT (~)
pemainbola[usia & ~klub & market].head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
97,Diego Costa,Chelsea,28,CF,1,50.0,4454,10.0,3.00%,196,2,Spain,0,4,5,1,0
102,Thibaut Courtois,Chelsea,25,GK,4,40.0,1260,5.5,18.50%,141,2,Belgium,0,3,5,1,0
105,Willian,Chelsea,28,RW,1,32.0,1165,7.0,9.00%,114,3,Brazil,0,4,5,1,0
107,Nemanja Matic,Chelsea,28,DM,2,35.0,892,5.0,5.00%,105,2,Serbia,0,4,5,1,0

## Mengenal 2D Indexing
indeksing menurut baris dan kolom sekaligus

In [15]:
# indexing 2D
pemainbola.loc[usia & ~klub & market,
              ['name','club','nationality','market_value']]

                   name               club nationality  market_value
96          Eden Hazard            Chelsea     Belgium          75.0
97          Diego Costa            Chelsea       Spain          50.0
102    Thibaut Courtois            Chelsea     Belgium          40.0
105             Willian            Chelsea      Brazil          32.0
107       Nemanja Matic            Chelsea      Serbia          35.0
108      N%27Golo Kante            Chelsea      France          50.0
217     Roberto Firmino          Liverpool      Brazil          38.0
218   Philippe Coutinho          Liverpool      Brazil          45.0
219          Sadio Mane          Liverpool     Senegal          40.0
241       Mohamed Salah          Liverpool       Egypt          35.0
244     Kevin De Bruyne    Manchester+City     Belgium          65.0
245       Sergio Aguero    Manchester+City   Argentina          65.0
246     Raheem Sterling    Manchester+City     England          45.0
249          Leroy Sane    Manchester+City     Germany          35.0
256         John Stones    Manchester+City     England          35.0
263      Bernardo Silva    Manchester+City    Portugal          40.0
264       Romelu Lukaku  Manchester+United     Belgium          50.0
265        David de Gea  Manchester+United       Spain          40.0
267          Paul Pogba  Manchester+United      France          75.0
275  Henrikh Mkhitaryan  Manchester+United     Armenia          35.0
380           Dele Alli          Tottenham     England          45.0
381          Harry Kane          Tottenham     England          60.0
382   Christian Eriksen          Tottenham     Denmark          40.0
386   Toby Alderweireld          Tottenham     Belgium          35.0